title: By Dasein
url: https://bydasein.com
description: >-
  A filmmaking company.
timezone: Australia/Brisbane
email: >-
  &#104;&#101;&#108;&#108;&#111;&#064;&#098;&#121;&#100;&#097;&#115;&#101;&#105;&#110;&#046;&#099;&#111;&#109;
copyright: >-
  &copy; By Dasein 2013&nbsp;&ndash;&nbsp;2020
date_format: >-
  %-d %B %Y
assets: /images/
exclude:
  - CNAME
  - README.md
